//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcomShoes_Webshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSize
    {
        public ProductSize()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int SizeID { get; set; }
        public int ProductSize1 { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
